# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: CyclonusOS
description: Bazzite with DankMaterialShell and Hyprland
base-image: ghcr.io/ublue-os/bazzite
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: /

  # Include your modular DNF and flatpak configs
  - from-file: ../config/repos-dms.yml
  - from-file: ../config/repos-common.yml
  - from-file: ../config/flatpaks.yml

  - type: script
    scripts:
      - add-nushell-repo.sh

  - type: signing