# yaml-language-server: $schema=https://schema.blue-build.org/module-v1.json
type: default-flatpaks
configurations:
  - notify: true
    scope: system
    install:
      - org.mozilla.firefox
      - org.gnome.Loupe
  - scope: user
