# yaml-language-server: $schema=https://schema.blue-build.org/module-v1.json[cite: 2]
type: dnf
repos:
  copr:
    - scottames/ghostty[cite: 2]
    - lihaohong/yazi[cite: 2]
install:
  packages:
    - ghostty[cite: 2]
    - yazi[cite: 2]
    - kitty[cite: 2]
    - micro[cite: 2]
    - make[cite: 2]
    - fzf[cite: 2]
    - ripgrep[cite: 2]
    - fd[cite: 2]
    - fastfetch[cite: 2]
    - fish[cite: 2]
    - qbittorrent[cite: 2]
    - emacs[cite: 2]
    - neovim[cite: 2]