# yaml-language-server: $schema=https://schema.blue-build.org/module-v1.json
type: dnf@v1
repos:
  copr:
    - scottames/ghostty
    - lihaohong/yazi
install:
  packages:
    - ghostty
    - yazi
    - kitty
    - micro
    - make
    - fzf
    - ripgrep
    - fd
    - fastfetch
    - fish
    - qbittorrent
    - emacs
    - neovim
